version: "2"

checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  method-complexity:
    enabled:  false

plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
  - "bin/gwin**"
  - "**.py"

exclude_paths:
- docs/*
- tools/*
- versioneer.py
- gwin/_version.py
