language: python

python:
  - '2.7'

before_install:
  - pip install pip setuptools --upgrade

  # install pegasus (don't install dependencies, psycopg2==2.6 is broken)
  - pip install `grep pegasus requirements.txt` --no-deps

install:
  - python -m pip install .

before_script:
  - python -m pip install coveralls "pytest>=2.8"

script:
  # run unit tests
  - coverage run ./setup.py test

  # run --help on all scripts (just to check for missing imports, etc)
  - |
    set -e
    for EXE in bin/gwin*; do
        echo "$ `basename $EXE` --help"
        `basename $EXE` --help 1> /dev/null
    done
    set +e

after_success:
  - coverage report
  - coveralls

cache: pip
