language: python

python:
  - '2.7'

before_install:
  - pip install pip setuptools --upgrade

install:
  - python -m pip install .

before_script:
  - python -m pip install coveralls "pytest>=2.8"

script:
  # run unit tests
  - coverage run ./setup.py test

  # run --help on all scripts (just to check for missing imports, etc)
  - |
    for EXE in bin/gwin*; do
        `basename $EXE` --help 1> /dev/null
    done

after_success:
  - coverage report
  - coveralls

cache: pip
